spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:25432/near_go
    username: postgres
    password: 123456
  jpa:
    database-platform:  org.hibernate.spatial.dialect.postgis.PostgisDialect # 设置数据库方言
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false # 去除无用的错误信息
    hibernate:
      ddl-auto: update